services:
  filebrowser:
    image: filebrowser/filebrowser
    restart: unless-stopped
    volumes:
      - ./data/filebrowser/srv:/srv
      - ./data/filebrowser/db:/db
      - ./data/filebrowser/config:/config
    networks:
      - proxy
    expose:
      - 8080:80

  notes:
    image: neosmemo/memos:stable
    restart: unless-stopped
    volumes:
      - ./data:/var/opt/memos
    environment:
      - MEMOS_MODE=prod
      - MEMOS_PORT=80
    networks:
      - proxy
    expose:
      - 8090:80

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 81:81
    volumes:
      - ./npm_data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - proxy
    
networks:
  proxy:
    driver: bridge
