services:
  filebrowser:
    image: filebrowser/filebrowser
    restart: unless-stopped
    volume:
      - ./data:/srv
    networks:
      - proxy
    expose:
      - "80"

  notes:
    image: neosmemo/memos:stable
    restart: unless-stopped
    volumes:
      - ./data:/var/opt/memos
    environment:
      - MEMOS_MODE=prod
      - MEMOS_PORT=80
    networks:
      - proxy
    expose:
      - "80"

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 81:81
    volumes:
      - ./npm_data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - proxy

  # proxy:
  #   image: nginx:alpine
  #   container_name: nginx-proxy
  #   restart: unless-stopped
  #   ports:
  #     - 80:80
  #     - 443:443
  #   environment:
  #     - DOMAIN=${DOMAIN}
  #     - NOTES_SUBDOMAIN=${NOTES_SUBDOMAIN}
  #     - FILES_SUBDOMAIN=${FILES_SUBDOMAIN}
  #   volumes:
  #     - ./proxy/:/etc/nginx/conf.d/:ro
  #     - /etc/letsencrypt:/etc/letsencrypt:ro
  #     - /var/www/certbot:/var/www/certbot
  #   networks:
  #     - proxy
  #   depends_on:
  #     - filebrowser
  #     - notes
  #   command: >
  #     /bin/sh -c "envsubst '$$DOMAIN $$NOTES_SUBDOMAIN $$FILES_SUBDOMAIN' < /etc/nginx/templates/nginx.template.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    
networks:
  proxy:
    driver: bridge
