services:
  filebrowser:
    image: filebrowser/filebrowser
    restart: unless-stopped
    volumes:
      - ./data/filebrowser/srv:/srv
      - ./data/filebrowser/db:/database
      - ./data/filebrowser/config:/config
    networks:
      - proxy
    expose:
      - 8080:80

  notes:
    image: neosmemo/memos:stable
    restart: unless-stopped
    volumes:
      - ./data/notes:/var/opt/memos
    environment:
      - MEMOS_MODE=prod
      - MEMOS_PORT=80
    networks:
      - proxy
    expose:
      - 8090:80

  gogs:
    image: gogs/gogs
    restart: unless-stopped
    volumes:
      - ./data/gogs:/data
    networks:
      - proxy
    expose:
      - "8070:3000"
      - "10022:22"

  home:
    build:
      context: ./home
      dockerfile: Dockerfile
    volumes:
      - ./home/public:/usr/share/nginx/html:ro
    expose:
      - "8060:80"
    restart: unless-stopped
    networks:
      - proxy


  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 81:81
    volumes:
      - ./data/npm:/data
      - ./data/letsencrypt:/etc/letsencrypt
    networks:
      - proxy

  # proxy:
  #   image: nginx:alpine
  #   container_name: nginx-proxy
  #   restart: unless-stopped
  #   ports:
  #     - 80:80
  #     - 443:443
  #   environment:
  #     - DOMAIN=${DOMAIN}
  #     - NOTES_SUBDOMAIN=${NOTES_SUBDOMAIN}
  #     - FILES_SUBDOMAIN=${FILES_SUBDOMAIN}
  #   volumes:
  #     - ./proxy/:/etc/nginx/conf.d/:ro
  #     - /etc/letsencrypt:/etc/letsencrypt:ro
  #     - /var/www/certbot:/var/www/certbot
  #   networks:
  #     - proxy
  #   depends_on:
  #     - filebrowser
  #     - notes
  #   command: >
  #     /bin/sh -c "envsubst '$$DOMAIN $$NOTES_SUBDOMAIN $$FILES_SUBDOMAIN' < /etc/nginx/templates/nginx.template.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    
networks:
  proxy:
    driver: bridge
